### PR TITLE
Add HEVC support.

### PR DESCRIPTION
**Pull request by PurrSevere**
Converts to HEVC for smaller file size at the cost of CPU resource.

### CODE REVIEW

**Comment by kuchenstrudel** [comment]
Great suggestion.

**Comment by jrudess** [comment]
Thanks, this was on my list to do, but I was thinking of a slightly different implementation, but I haven't put the full infrastructure in place yet.

Rather than making the current post-process script take a new argument, I wanted to make the choice of post-process scripts configurable per site.   So instead of adding a new switch for hevc, I'd like a new postprocess_ffmpeg_x265.sh script.

e.g. in the site.yml there will be:
```
postprocess: scripts/postprocess_ffmpeg.sh
```
or
```
postprocess: scripts/postprocess_ffmpeg_x265.sh
```

I'll put all the code in for this, and then could you resubmit this PR as just the implementation of postprocess_ffmpeg_x265.sh?

**Comment by PurrSevere** [comment]
Sure thing!

**Comment by jrudess** [comment]
What commit version do you have?  I believe I have already fixed this in master-branch, and the file size checking is supposed to shut off during post-processing.  However, after making that that fix I did  "counter=undefined" print once which should never be able to happen.   But I haven't been able to reproduce it.

**Pull request closed without merging**
